2025-02-04 08:18:43,773 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\XaMeLeoH\PycharmProjects\Urban\pythonProject2\module_12\module_12_4\tests_12_4.py", line 21, in test_run
    test = module_12_4.Runner(000)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XaMeLeoH\PycharmProjects\Urban\pythonProject2\module_12\module_12_4\module_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-02-04 08:18:43,775 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\XaMeLeoH\PycharmProjects\Urban\pythonProject2\module_12\module_12_4\tests_12_4.py", line 10, in test_walk
    test = module_12_4.Runner('Mark', -5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XaMeLeoH\PycharmProjects\Urban\pythonProject2\module_12\module_12_4\module_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
